-- Rode esse script uma vez no SQL Editor do Supabase (projeto > SQL Editor > New query).
-- Equivalente ao schema que estava em server/db.js (SQLite).

create table if not exists searches (
  id bigint generated by default as identity primary key,
  niche text not null,
  location text not null,
  requested_count integer not null,
  status text not null default 'running',
  processed integer not null default 0,
  error text,
  created_at timestamptz not null default now()
);

create table if not exists leads (
  id bigint generated by default as identity primary key,
  search_id bigint references searches(id) on delete set null,
  name text not null,
  category text,
  address text,
  phone text,
  website text,
  has_website boolean not null default false,
  email text,
  instagram text,
  facebook text,
  linkedin text,
  whatsapp text,
  tiktok text,
  rating real,
  reviews_count integer,
  maps_url text unique,
  qualification text not null default 'nao_avaliado'
    check (qualification in ('nao_avaliado', 'qualificado', 'descartado')),
  status text not null default 'nao_contatado'
    check (status in ('nao_contatado', 'potencial', 'contatado', 'sem_resposta', 'em_negociacao', 'fechado', 'perdido')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_leads_search_id on leads(search_id);
create index if not exists idx_leads_has_website on leads(has_website);
create index if not exists idx_leads_qualification on leads(qualification);
create index if not exists idx_leads_status on leads(status);

-- O servidor acessa com a service_role key (bypassa RLS), então não precisa de
-- policies. RLS fica desativado por padrão nessas tabelas recém-criadas.
